# Generated by Django 2.1.7 on 2019-04-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tel_num', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_created=True)),
                ('descriptions', models.CharField(default='비어있음..', max_length=128)),
                ('order_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cnt', models.PositiveIntegerField(default=1)),
                ('amount_of_credited_mileage', models.PositiveIntegerField()),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
                ('product_owned_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='related_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_set_included_order',
            field=models.ManyToManyField(related_name='ordered_product_set', through='orm_practice_app.OrderedProduct', to='orm_practice_app.Product'),
        ),
    ]
