# Generated by Django 2.1.7 on 2019-04-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_owned_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.Company'),
        ),
    ]
