# Generated by Django 2.1.7 on 2019-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice_app', '0002_auto_20190420_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tel_num',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
