# Generated by Django 2.1.7 on 2019-05-06 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm_practice_app', '0003_auto_20190420_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('descriptions', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='서울시,안양시,...', max_length=128)),
                ('gu', models.CharField(default='', help_text='서초구, 강남구,...,', max_length=128)),
                ('detail', models.CharField(default='', help_text='104동 101호', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_num', models.CharField(max_length=128, null=True)),
                ('owned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mileage',
            name='owned_userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.UserInfo'),
        ),
        migrations.AddField(
            model_name='mileage',
            name='related_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm_practice_app.Order'),
        ),
    ]
