# Generated by Django 2.1.7 on 2019-05-06 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice_app', '0004_auto_20190506_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
